/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransparenciaRouteImport } from './routes/transparencia'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ProductoRouteImport } from './routes/producto'
import { Route as ManifiestoRouteImport } from './routes/manifiesto'
import { Route as ListaDeEsperaRouteImport } from './routes/lista-de-espera'
import { Route as BrandBookRouteImport } from './routes/brand-book'
import { Route as IndexRouteImport } from './routes/index'

const TransparenciaRoute = TransparenciaRouteImport.update({
  id: '/transparencia',
  path: '/transparencia',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductoRoute = ProductoRouteImport.update({
  id: '/producto',
  path: '/producto',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifiestoRoute = ManifiestoRouteImport.update({
  id: '/manifiesto',
  path: '/manifiesto',
  getParentRoute: () => rootRouteImport,
} as any)
const ListaDeEsperaRoute = ListaDeEsperaRouteImport.update({
  id: '/lista-de-espera',
  path: '/lista-de-espera',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandBookRoute = BrandBookRouteImport.update({
  id: '/brand-book',
  path: '/brand-book',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brand-book': typeof BrandBookRoute
  '/lista-de-espera': typeof ListaDeEsperaRoute
  '/manifiesto': typeof ManifiestoRoute
  '/producto': typeof ProductoRoute
  '/sobre': typeof SobreRoute
  '/transparencia': typeof TransparenciaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brand-book': typeof BrandBookRoute
  '/lista-de-espera': typeof ListaDeEsperaRoute
  '/manifiesto': typeof ManifiestoRoute
  '/producto': typeof ProductoRoute
  '/sobre': typeof SobreRoute
  '/transparencia': typeof TransparenciaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brand-book': typeof BrandBookRoute
  '/lista-de-espera': typeof ListaDeEsperaRoute
  '/manifiesto': typeof ManifiestoRoute
  '/producto': typeof ProductoRoute
  '/sobre': typeof SobreRoute
  '/transparencia': typeof TransparenciaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brand-book'
    | '/lista-de-espera'
    | '/manifiesto'
    | '/producto'
    | '/sobre'
    | '/transparencia'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brand-book'
    | '/lista-de-espera'
    | '/manifiesto'
    | '/producto'
    | '/sobre'
    | '/transparencia'
  id:
    | '__root__'
    | '/'
    | '/brand-book'
    | '/lista-de-espera'
    | '/manifiesto'
    | '/producto'
    | '/sobre'
    | '/transparencia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandBookRoute: typeof BrandBookRoute
  ListaDeEsperaRoute: typeof ListaDeEsperaRoute
  ManifiestoRoute: typeof ManifiestoRoute
  ProductoRoute: typeof ProductoRoute
  SobreRoute: typeof SobreRoute
  TransparenciaRoute: typeof TransparenciaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transparencia': {
      id: '/transparencia'
      path: '/transparencia'
      fullPath: '/transparencia'
      preLoaderRoute: typeof TransparenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producto': {
      id: '/producto'
      path: '/producto'
      fullPath: '/producto'
      preLoaderRoute: typeof ProductoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifiesto': {
      id: '/manifiesto'
      path: '/manifiesto'
      fullPath: '/manifiesto'
      preLoaderRoute: typeof ManifiestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lista-de-espera': {
      id: '/lista-de-espera'
      path: '/lista-de-espera'
      fullPath: '/lista-de-espera'
      preLoaderRoute: typeof ListaDeEsperaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-book': {
      id: '/brand-book'
      path: '/brand-book'
      fullPath: '/brand-book'
      preLoaderRoute: typeof BrandBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandBookRoute: BrandBookRoute,
  ListaDeEsperaRoute: ListaDeEsperaRoute,
  ManifiestoRoute: ManifiestoRoute,
  ProductoRoute: ProductoRoute,
  SobreRoute: SobreRoute,
  TransparenciaRoute: TransparenciaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
